NM: NeedleMatch.cpp
	g++ NeedleMatch.cpp -o NeedleMatch -lm  -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs
NMC: NeedleMatchCuda.cu
	nvcc NeedleMatchCuda.cu -o NeedleMatchCuda -lm -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs